FROM python:3.11.9

WORKDIR /app
COPY ./requirements.txt /app/
RUN pip install -r requirements.txt
COPY ./back ./back
EXPOSE 5000
ENV FLASK_APP=./back/api/app.py
CMD ["flask", "run", "--host", "0.0.0.0"]